# Generated by Django 3.1.7 on 2021-12-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('size', models.IntegerField(default=0, null=True)),
                ('price', models.FilePathField(default=0, null=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
